### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by JosefUtbult**
Add Swedish translation. It is not integrated yet, but the `sv.ts` file is translated. The language name in the dropdown menu should be "Svenska (Swedish)".

### CODE REVIEW

**Comment by phibr0** [comment]
Obsidian itself doesn't have a swedish translation, does it?

**Comment by phibr0** [comment]
So this plugin uses the language that Obsidian itself uses, and thus doesn't have it's own setting for that. It seems like Obsidian itself isn't translated to swedish, so this translation wouldn't be used.

**Comment by obrignoni** [comment]
Hello @phibr0, 

Regarding the same topic. I was about to start working on the pt.ts (European Portuguese) translation. I see the empty file is in this project but not sure if PT is in Obsidian itself.

Should I send a PR for it?

**Comment by phibr0** [comment]
image

PT is available in Obsidian, would be very nice if you fill it out!
Oh and @JosefUtbult, I know it's a lot of work, but if you like, you can try and add a Swedish translation to Obsidian itself first: https://github.com/obsidianmd/obsidian-translations/blob/master/se.json

**Comment by obrignoni** [comment]
Sounds good. I think I missed it the first time expecting it to be right before `Portugues do Brazil`. I see its further down.

I am also working on adding a new API provider, Linguee. I will send the translation on its own PR.

**Comment by JosefUtbult** [comment]
Ah okay. I might have misunderstood how it worked in that case. Sorry :)

**Pull request closed without merging**
